name: PHPStan Analysis

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  phpstan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: bcmath, bz2, curl, gd, intl, mbstring, mysql,mysqlnd, mysqli, opcache, pdo_mysql, pgsql, json,soap, xml, zip

      - name: Install Composer dependencies
        run: |
          find . -maxdepth 4 -name composer.json -exec bash -c 'composer --no-ansi --working-dir="`dirname {}`" install --optimize-autoloader' ";"

      - name: Install PHPStan
        run: |
          composer require --dev phpstan/phpstan

      - name: Run PHPStan
        run: |
          echo "Running PHPStan with configuration file..."
          vendor/bin/phpstan analyse --configuration=phpstan.neon
